Updating packman to 6.41

diff --git a/tools/packman/packman b/tools/packman/packman
--- a/tools/packman/packman
+++ b/tools/packman/packman
@@ -22,7 +22,7 @@ else
 	PM_CURL_SILENT="-s -S"
 	PM_WGET_QUIET="--quiet"
 fi
-PM_PACKMAN_VERSION=6.33.2
+PM_PACKMAN_VERSION=6.41
 
 # This is necessary for newer macOS
 if [ `uname` == 'Darwin' ]; then
@@ -30,33 +30,28 @@ if [ `uname` == 'Darwin' ]; then
 	export LANG=en_US.UTF-8
 fi
 
-# Specify where packman command exists
-export PM_INSTALL_PATH="$(realpath "$(dirname "${BASH_SOURCE}")")"
-
-add_packages_root_to_file()
-{
-	FILE_PATH=$1
-	if [ -f "$FILE_PATH" ]; then
-		if ! grep -Fq "PM_PACKAGES_ROOT" $FILE_PATH ; then
-			echo "Adjusting $FILE_PATH"
-			echo -e "export PM_PACKAGES_ROOT=\$HOME/packman-repo\n" >> $FILE_PATH
-		fi
-	fi
+# We cannot rely on realpath, it isn't installed on macOS and some Linux distros
+get_abs_filename() {
+  echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
 }
+
+# Specify where packman command exists
+export PM_INSTALL_PATH="$(get_abs_filename "$(dirname "${BASH_SOURCE}")")"
 
 # The packages root may already be configured by the user
 if [ -z "${PM_PACKAGES_ROOT:-}" ]; then
-	# Set variable permanently using .profile for this user (if exists)
-	add_packages_root_to_file ~/.profile
-	add_packages_root_to_file ~/.bashrc
 	# Set variable temporarily in this process so that the following execution will work
-	export PM_PACKAGES_ROOT="${HOME}/packman-repo"
+	if [ `uname` == 'Darwin' ]; then
+		export PM_PACKAGES_ROOT="/Library/Caches/packman"
+	else
+		export PM_PACKAGES_ROOT="/var/tmp/packman"
+	fi
 fi
 
 # Ensure the packages root path exists:
 if [ ! -d "$PM_PACKAGES_ROOT" ]; then
-	echo "Creating packman packages repository at $PM_PACKAGES_ROOT"
-	mkdir -p "$PM_PACKAGES_ROOT"
+	echo "Creating packman packages cache at $PM_PACKAGES_ROOT"
+	mkdir -p -m a+rwx "$PM_PACKAGES_ROOT"
 fi
 
 fetch_file_from_s3()
@@ -72,18 +67,28 @@ fetch_file_from_s3()
 	fi
 }
 
+generate_temp_file_name()
+{
+	if [ `uname` == "Darwin" ]; then
+		local tmpfile=`mktemp -t packman`
+	else
+		local tmpfile=`mktemp -t packman.XXXXXXXX`
+	fi
+	echo "$tmpfile"
+}
+
 install_python()
 {
 	PLATFORM=`uname`
 	PROCESSOR=`uname -m`
-	PYTHON_VERSION=3.7.9
+	PYTHON_VERSION=3.7.12
 
 	if [ $PLATFORM == 'Darwin' ]; then
 		PYTHON_PACKAGE=$PYTHON_VERSION-macos-x86_64
 	elif [ $PLATFORM == 'Linux' ] && [ $PROCESSOR == 'x86_64' ]; then
 		PYTHON_PACKAGE=$PYTHON_VERSION-linux-x86_64
 	elif [ $PLATFORM == 'Linux' ] && [ $PROCESSOR == 'aarch64' ]; then
-		PYTHON_PACKAGE=$PYTHON_VERSION-177-linux-aarch64
+		PYTHON_PACKAGE=$PYTHON_VERSION-linux-aarch64
 	else
 		echo "Operating system not supported"
 		exit 1
@@ -97,10 +102,12 @@ install_python()
 	export PM_PYTHON="$PYTHON_INSTALL_FOLDER/python"
 
 	if [ ! -f "$PM_PYTHON" ]; then
-		fetch_file_from_s3 "python@$PYTHON_PACKAGE.tar.gz" "/tmp/python@$PYTHON_PACKAGE.tar.gz"
+		PYTHON_PACKAGE_TMP=$(generate_temp_file_name)
+		fetch_file_from_s3 "python@$PYTHON_PACKAGE.tar.gz" "$PYTHON_PACKAGE_TMP"
 		if [ "$?" -eq "0" ]; then
 			echo "Unpacking python"
-			tar -xf "/tmp/python@$PYTHON_PACKAGE.tar.gz" -C "$PYTHON_INSTALL_FOLDER"
+			tar -xf "$PYTHON_PACKAGE_TMP" -C "$PYTHON_INSTALL_FOLDER"
+			rm "$PYTHON_PACKAGE_TMP"
 		else
 			echo "Failed downloading the Python interpreter"
 			exit $?
@@ -121,18 +128,22 @@ if [ -z "${PM_MODULE_DIR_EXT:-}" ]; then
 else
     PM_MODULE_DIR="$PM_MODULE_DIR_EXT"
 fi
-export PM_MODULE="$PM_MODULE_DIR/packman.py"
+export PM_MODULE="$PM_MODULE_DIR/run.py"
 
 # Ensure the packman package exists:
 if [ ! -f "$PM_MODULE" ]; then
+	# Remove a previously corrupt packman-common if it's there
+	if [ -d "$PM_MODULE_DIR" ]; then
+		rm -rf "$PM_MODULE_DIR"
+	fi
 	PM_MODULE_PACKAGE="packman-common@$PM_PACKMAN_VERSION.zip"
-	TARGET="/tmp/$PM_MODULE_PACKAGE"
+	TARGET=$(generate_temp_file_name)
 	# We always fetch packman from S3:
-	fetch_file_from_s3 $PM_MODULE_PACKAGE $TARGET
+	fetch_file_from_s3 "$PM_MODULE_PACKAGE" "$TARGET"
 	if [ "$?" -eq "0" ]; then
 		echo "Unpacking ..."
 		"$PM_PYTHON" -S -s -u -E "$PM_INSTALL_PATH/bootstrap/install_package.py" "$TARGET" "$PM_MODULE_DIR"
-		rm $TARGET
+		rm "$TARGET"
 	else
 		echo "Failure while fetching packman module from S3!"
 		exit 1
@@ -174,11 +185,6 @@ if [ -f "$PM_VAR_PATH" ]; then
     rm -f "$PM_VAR_PATH"
 fi
 
-# Return the exit code from python
-if [ "$exit_code" != 0 ]; then
-    exit "$exit_code"
-fi
-
 # avoid leaking -e and -u into the host script if they weren't originally set
 if [[ ! ( "$SAVED_SETTINGS" =~ e ) ]]; then
     set +e
@@ -188,3 +194,7 @@ if [[ ! ( "$SAVED_SETTINGS" =~ u ) ]]; then
     set +u
 fi
 
+# Return the exit code from python
+if [ "$exit_code" != 0 ]; then
+    exit "$exit_code"
+fi
